services:
  web:
    build: .
    container_name: backend
    image: backend-image:latest
    ports:
      - "8080:8080"
    networks:
      - project-bridge

networks:
  project-bridge:
    name: project-bridge
    driver: bridge